# Generated by Django 5.1.7 on 2025-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("manager", "Manager")],
                default="user",
                max_length=50,
            ),
        ),
    ]
