# Generated by Django 5.1.7 on 2025-05-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
    ]
