# Generated by Django 5.1.7 on 2025-04-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "low"), (2, "medium"), (3, "high")], default=1
            ),
        ),
    ]
