# Generated by Django 5.1.7 on 2025-04-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[(1, "to_do"), (2, "in_progress"), (3, "done")],
                default=1,
            ),
        ),
    ]
