# Generated by Django 5.1.7 on 2025-05-03 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название категории"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор комментария",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Текст комментария"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название тэга"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=tasks.models.default_deadline,
                verbose_name="Срок выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание задачи"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ManyToManyField(
                related_name="task_executors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель задачи",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель задачи",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "low"), (2, "medium"), (3, "high")],
                default=1,
                verbose_name="Приоритет задачи",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[(1, "to_do"), (2, "in_progress"), (3, "done")],
                default=1,
                verbose_name="Статус выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название задачи"),
        ),
    ]
