"""Django settings for tasks_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# настройки работы приложения за обратным прокси:
# говорю джанго, что проект размещен не в корне:
# FORCE_SCRIPT_NAME = "/tasks_project"
# говорю джанге реальный хост, а не то что проксирует nginx,
# для корректного формирования ссылок:
# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# load_dotenv()
# выбираю нужный .env файл:
ENV_FILE = os.getenv("DJANGO_ENV_FILE", ".env.dev")  # если не передано-берет '.env.dev'
load_dotenv(dotenv_path=ENV_FILE)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DOMAIN_NAME = os.getenv("DOMAIN_NAME")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise Exception("SECRET_KEY is missing, set it in environment")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",  # auto import all models, ipython-autocomplete
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "authapp",
    "tasks",
    "django_filters",
    "drf_spectacular",
    "django_celery_beat",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tasks_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tasks_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# Основные настройки базы данных (для продакшн-среды)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Если запускаются тесты, меняем базу данных на SQLite (in-memory)
if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",  # Используем in-memory базу данных для тестов
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        "authapp.authentication.CookieJWTAuthentication",
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    # 'DEFAULT_THROTTLE_RATES': {
    #         'user': '5/hour',
    #         'anon': '10/minute',
    #     },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,  # рефреши после использования обновляются
    "BLACKLIST_AFTER_ROTATION": True,  # а после обновления добавляются в черный список
    "AUTH_COOKIE": "access_token",  # где сервер будет искать токен -
    # request.COOKIES["access_token"]
    "SIGNING_KEY": SECRET_KEY,  # JWT подписываются этим ключом
    # "AUTH_HEADER_TYPES": ("Bearer",),  # для передачи в заголовках
    "AUTH_COOKIE_HTTP_ONLY": True,  # делает cookie невидимым для JavaScript-защита
    "AUTH_COOKIE_SECURE": True,  # чтобы куки отправлялись токлько по HTTPS;
    # в localhost можно отключить, но включать в продакшене.
    "AUTH_COOKIE_SAMESITE": "Lax",  # чтобв cookie отправлялись только
    # при навигации по сайту; предотвращение CSRF-атак.
}

SECURE_COOKIE = False  # True  # Только через HTTPS, если в продакшене

CORS_ALLOW_CREDENTIALS = True  # Для разрешения отправки cookies

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = True  # шифрование данных
EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER"
)  # адрес с которого юзерам будут приходить подтверждения регистрации и пр
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

SPECTACULAR_SETTINGS = {
    "TITLE": "Your Project API",
    "DESCRIPTION": "Your project description",
    "VERSION": "2.0.0",
    #'SERVE_ROOT': '/tasks_project/schema/',
    #'SCHEMA_PATH_PREFIX': '/tasks_project',
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVERS": [{"url": "http://95.31.180.169:5816/tasks_project"}],
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")  # для хранения результатов
CELERY_BEAT_SCHEDULER = os.getenv("CELERY_BEAT_SCHEDULER")
CELERY_ENABLE_UTC = os.getenv("CELERY_ENABLE_UTC")
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] [%(levelname)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "email_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "formatter": "verbose",
            "filename": "logs/email_tasks.log",
        },
        "notify_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "formatter": "verbose",
            "filename": "logs/notification_tasks.log",
        },
        "comment_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "formatter": "verbose",
            "filename": "logs/comment_factory.log",
        },
    },
    "loggers": {
        "email_tasks": {
            "handlers": ["email_file"],
            "level": "INFO",
            "propagate": False,
        },
        "notification_tasks": {
            "handlers": ["notify_file"],
            "level": "INFO",
            "propagate": False,
        },
        "comment_factory": {
            "handlers": ["comment_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# handlers — описывают куда и как логировать (файл, консоль, e-mail и т. д.).
# loggers — описывают что именно логировать (от какого логгера, на каком уровне,
# с какими обработчиками).
