name: basic CI

on:
  push:
    branches: [improvements]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025  # порт для тестового SMTP

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pre-commit

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

    - name: Lint with ruff
      run: make lint

    - name: Create .env for CI
      run: cp .env.dev .env

    - name: Check for missing migrations
      run: python manage.py makemigrations --check --dry-run

    - name: Run tests with coverage and checks
      run: make check
